### PR TITLE
Add simplified pipeline construction interface

### PR DESCRIPTION
**Pull request by andruekonst**
The main idea is to replace builder method calls like `builder.RFC(...)` with placeholders constructors e.g. `RFC(...)` to support editor suggestions for arguments of underlying block constructors.

The implementation is based on one global variable corresponding to the active builder instance. The new pipeline builders can be used as context managers to define pipeline in `with` block. For example:

```
with BetterFunctionalPipelineBuilder() as b:
    # there every placeholder instance can get access to `b` through the global function `get_active_builder()`
    x = Input(  )()
    #         ^ here an IDE can suggest arguments, because no dynamic resolution is required

with BetterFunctionalPipelineBuilder() as b2:
    z = Input()()
    rf = RFC(random_state=12345)
    proba = rf(z)
    # rf(x)  # <- cannot execute this, since `b` and `b2` are not connected

with BetterFunctionalPipelineBuilder() as b3:
    with BetterFunctionalPipelineBuilder() as b4:  # <- exception will be raised
        ... # this is forbidden too
```

Here `Input()`, `RFC(...)` are placeholders (of type `PlaceholderFunction`), which operate with the active builder and return block wrappers when called.

The argument types and docstrings are emplaced into placeholders by using `functools.wraps`, which is usually evaluated in completion / intellisense systems for making suggestions.

### CODE REVIEW

**Review by Stasychbr — APPROVED** [review]
I like the idea, but defining extra class for the placeholder seems little bit awkward to me. I guess that all of the listed placeholders will be included as the native part of the bosk, but maybe it also makes sense if we add a static method for getting a placeholder in AutoBlock (or maybe even BaseBlock)? Is it possible to get an AutoBlock's placeholder and inference its type to get the ide's hints? Or maybe AutoBlock can have some method like link_with_builder to obtain placeholder's functionality out of box?

**Comment by andruekonst** [comment]
I agree that writing boilerplate code for IDE suggestions does not seem ok.

Alternatively we can just extend the `BaseBlock` interface, allowing blocks to be *called*, implementing the same functionality as `PlaceholderFunction(self)`. More precisely, we can add `__call__` method to the `BaseBlock` interface, which will have access to the default builder.

Disadvantages of the approach:
- dependency loop between `BaseBlock` and `PipelineBuilder` will appear;
- the functional interface will be considered as a default, while basically functional pipeline construction is just a *syntactic sugar*;
- Each block by used naming convention will have name like `...Block`, making code harder to read, e.g.: `RFCBlock(n_estimators=123)(X=InputBlock()(), X=TargetInputBlock()())` looks less preferable to `RFC(n_estimators=123)(X=Input()(), X=TargetInput()())`.

**Comment by andruekonst** [comment]
The approach implemented in the example allows also to implement custom behavior for a specific input block.
It can be useful in case when we want to add suggestions for a placeholder function arguments. Note, that currently they are taken as varargs: https://github.com/NTAILab/bosk/pull/69/commits/b075a6823b15c2b9fe2767696d65c3f03e0f4519#diff-109d65c26cfb96fcffecc92c52aa80619b801df254e868e2813900b456bc2aa6R84. But block developers can specify the exact amount and names of arguments for the implemented blocks.

For example, with current implementation it can be done by:

```
class Input(PlaceholderFunction):
     @wraps(InputBlock.__init__)
     def __init__(self, *args, **kwargs):
         super().__init__(InputBlock(*args, **kwargs))
    def __call__(self, X):
        """Pass arguments to the Input block.

        Args:
            X: Input data tensor of shape (n_samples, n_features).

        Returns:
            Block wrapper.
        """"
        return super().__call__(X)
```

Advantages:
- a block input arguments suggestion in an IDE;
- additional block-specific argument checks can be implemented.

Disadvantages:
- arguments description in a block definition and its placeholder should be consistent, and this can be achieved only by manual checks;
- for each existing block, the placeholder function should be defined manually.

To alleviate the later disadvantage, we can generate placeholders for blocks automatically (if the custom implementation does not exist), at block import step.

**Comment by andruekonst** [comment]
The final solution:

- Add `bosk.block.placeholder.PlaceholderMixin` mixin that can add placeholder functionality to any block (i.e. adds `__call__` method);
- Inherit `AutoBlock` (generated by `@auto_block`) from `PlaceholderMixin` – **any auto block is a placeholder** by default;
- Inherit each block other than `AutoBlock` from `PlaceholderMixin` via refactoring;
- **Rename all blocks in the zoo**: remove `Block` word from each block name;
- Add stubs for backward compatibility for each block: `${block_name}Block = ${block_name}`, e.g. `InputBlock = Input`;
- New blocks **should not contain** `Block` at the end of their names and should be derived from `PlaceholderMixin`.

After the changes, the following code can be used to construct a pipeline:

```python
from bosk.block.zoo.input_plugs import Input, TargetInput
from bosk.block.zoo.models.classification import RFC, ETC
from bosk.block.zoo.data_conversion import Average, Concat, Argmax, Stack
from bosk.block.zoo.metrics import RocAuc

with FunctionalPipelineBuilder() as b:
    X, y = Input()(), TargetInput()()
    rf_1 = RFC(random_state=42, **forest_params)(X=X, y=y)
    et_1 = ETC(random_state=42, **forest_params)(X=X, y=y)
    concat_1 = Concat(['X', 'rf_1', 'et_1'])(X=X, rf_1=rf_1, et_1=et_1)
    rf_2 = RFC(random_state=42, **forest_params)(X=concat_1, y=y)
    et_2 = ETC(random_state=42, **forest_params)(X=concat_1, y=y)
    concat_2 = Concat(['X', 'rf_2', 'et_2'])(X=X, rf_2=rf_2, et_2=et_2)
    rf_3 = RFC(random_state=42, **forest_params)(X=concat_2, y=y)
    et_3 = ETC(random_state=42, **forest_params)(X=concat_2, y=y)
    stack_3 = Stack(['rf_3', 'et_3'], axis=1)(rf_3=rf_3, et_3=et_3)

    average_3 = Average(axis=1)(X=stack_3)
    argmax_3 = Argmax(axis=1)(X=average_3)

    rf_1_roc_auc = RocAuc()(gt_y=y, pred_probas=rf_1)
    roc_auc = RocAuc()(gt_y=y, pred_probas=average_3)

pipeline = b.build({'X': X, 'y': y}, {'probas': average_3})
```

**Pull request merged**
